default_language_version:
  python: python3.9

default_stages: [commit, push]

repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--check"]

  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black
        args: ["--check"]
        language_version: python3.9

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy

  - repo: https://github.com/PyCQA/pylint
    rev: v2.14.5
    hooks:
      - id: pylint
        args: ["quconot"]
        additional_dependencies:
          - pyenchant

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: file-contents-sorter
        files: "wordlist.txt"
