name: Quality checks

on: [push]

jobs:
  run_quality_cheks:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - uses: actions/checkout@v4.1.0
      - run: pip install pyenchant
      - run: pip install -e .
      - name: Run quality checks
        uses: marian-code/python-lint-annotate@v3
        with:
          python-root-list: "quconot"
          use-black: true
          use-isort: true
          use-mypy: true
          extra-mypy-options: --ignore-missing-imports --namespace-packages
          use-pycodestyle: false
          use-pydocstyle: false
          use-pylint: false
          use-flake8: true
          use-vulture: true
