name: Quality checks

on: [push]

jobs:
  run_quality_cheks:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - uses: actions/checkout@v3
      - run: pip install pyenchant
      - name: Run quality checks
        uses: pylint-dev/pylint@v3.0.1
        with:
          python-root-list: "quconot"
          use-pylint: false
          use-pycodestyle: false
          use-flake8: true
          use-mypy: true
          use-black: true
          use-isort: true
          extra-mypy-options: --ignore-missing-imports --namespace-packages
