name: Tests

on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: [3.9]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies and the package
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
          pip install -e .
      - name: Run unit tests
        run: python -m pytest --cov=quconot --cov-report=xml
      - name: Report coverage
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
